#spring.application.name=RestApiSample
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://google.com # origins permitidas por este serviço
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  application:
    name: RestApiSample
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: admin123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
  jackson:
      property-naming-strategy: SNAKE_CASE
  spring-doc:
    path-to-match:
      - /api/**/v1/**
      - /auth/**
    swagger-ui:
      use-root-path: true
